#!/usr/bin/env python3
import json
import mimetypes
import os
import posixpath
import re
import subprocess
from http.server import SimpleHTTPRequestHandler, ThreadingHTTPServer
from pathlib import Path
from urllib.parse import quote, unquote, urlparse


WEB_ROOT = Path(os.environ.get("PROMOCASTER_CONTROL_WEB_ROOT", "web")).resolve()
DATA_DIR = Path(os.environ.get("PROMOCASTER_CONTROL_DATA_DIR", ".")).resolve()
CLIENTS_FILE = Path(os.environ.get("PROMOCASTER_CONTROL_CLIENTS_FILE", "clients.yml")).resolve()
REPOS_DIR = Path(os.environ.get("PROMOCASTER_CONTROL_REPOS_DIR", DATA_DIR / "repos")).resolve()
SYNC_DIR = Path(os.environ.get("PROMOCASTER_CONTROL_SYNC_DIR", DATA_DIR / "sync")).resolve()
SSH_DIR = Path(os.environ.get("PROMOCASTER_CONTROL_SSH_DIR", DATA_DIR / "ssh")).resolve()
GITHUB_KEY = Path(os.environ.get("PROMOCASTER_CONTROL_GITHUB_KEY", SSH_DIR / "github_writer_key")).resolve()
BIND = os.environ.get("PROMOCASTER_CONTROL_BIND", "127.0.0.1")
PORT = int(os.environ.get("PROMOCASTER_CONTROL_PORT", "8080"))
MAX_JSON_BODY_BYTES = int(os.environ.get("PROMOCASTER_CONTROL_MAX_JSON_BODY_BYTES", str(2 * 1024 * 1024)))


def load_clients():
    clients = {}
    if not CLIENTS_FILE.exists():
        return clients

    current = ""
    for raw_line in CLIENTS_FILE.read_text(encoding="utf-8").splitlines():
        if raw_line.startswith("  ") and not raw_line.startswith("    ") and raw_line.strip().endswith(":"):
            current = raw_line.strip()[:-1]
            clients[current] = {}
            continue
        if current and raw_line.startswith("    ") and ":" in raw_line:
            key, value = raw_line.strip().split(":", 1)
            clients[current][key] = clean_yaml_scalar(value.strip())
    return clients


def repo_checkout_name(repo_url):
    name = repo_url.rstrip("/").rsplit("/", 1)[-1]
    if name.endswith(".git"):
        name = name[:-4]
    return name or "repo"


def client_repo_name(client):
    repo = load_clients().get(client, {}).get("repo", "")
    if repo:
        return repo_checkout_name(repo)
    return client


def client_branch(client):
    return load_clients().get(client, {}).get("branch", "master") or "master"


def clean_yaml_scalar(value):
    value = value.split(" #", 1)[0].strip()
    if (value.startswith('"') and value.endswith('"')) or (value.startswith("'") and value.endswith("'")):
        value = value[1:-1]
    return value


def media_type_for_name(name):
    return "video" if name.lower().endswith(".mp4") else "image"


def slide_from_entry(client, entry):
    name = entry.get("name") or entry.get("file") or ""
    slide_type = media_type_for_name(name)
    duration = int(entry.get("time") or entry.get("duration") or entry.get("durationMs") or 10000)
    return {
        "name": name,
        "src": f"/api/clients/{quote(client, safe='')}/media/{quote(name, safe='')}",
        "type": slide_type,
        "durationMs": None if slide_type == "video" else duration,
        "maxDurationMs": duration if slide_type == "video" and duration else None,
        "startsOn": entry.get("starts") or entry.get("startsOn") or "",
        "expiresOn": entry.get("expires") or entry.get("expiresOn") or "",
    }


def referenced_media_names(deck_data):
    names = set()
    for location in deck_data.get("locations", []):
        for slide in location.get("slides", []):
            name = slide.get("name") or ""
            if name:
                names.add(name)
    return names


def location_names(deck_data):
    return [location.get("name", "") for location in deck_data.get("locations", [])]


def yaml_quote(value):
    value = str(value)
    if not value:
        return '""'
    if re.fullmatch(r"[A-Za-z0-9._/-]+", value):
        return value
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def deck_to_media_yml(deck_data):
    lines = [
        "####",
        "# Promocaster slide deck configuration",
        "# Generated by Promocaster Control",
        "####",
        "",
    ]

    for location in deck_data.get("locations", []):
        name = location.get("name", "")
        if not re.fullmatch(r"[A-Za-z0-9_-]+", name):
            raise ValueError(f"invalid location name: {name}")
        lines.append(f"{name}:")
        lines.append("")
        for slide in location.get("slides", []):
            slide_name = slide.get("name", "")
            if not slide_name or "/" in slide_name or "\\" in slide_name:
                raise ValueError(f"invalid slide filename: {slide_name}")
            slide_type = slide.get("type") or media_type_for_name(slide_name)
            if slide_type == "video":
                duration = int(slide.get("maxDurationMs") or slide.get("durationMs") or 0)
            else:
                duration = int(slide.get("durationMs") or 10000)
            starts_on = slide.get("startsOn") or slide.get("starts") or ""
            expires_on = slide.get("expiresOn") or slide.get("expires") or ""
            lines.append(f"- name: {yaml_quote(slide_name)}")
            if duration:
                lines.append(f"  time: {max(duration, 1000)}")
            lines.append(f"  starts: {yaml_quote(starts_on)}")
            lines.append(f"  expires: {yaml_quote(expires_on)}")
            lines.append("")
        if not location.get("slides"):
            lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def parse_media_yml(client, media_yml):
    locations = []
    current = None
    current_slide = None
    key_pattern = re.compile(r"^[A-Za-z0-9_-]+:\s*$")

    for raw_line in media_yml.read_text(encoding="utf-8").splitlines():
        line = raw_line.rstrip()
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            continue

        if not raw_line.startswith((" ", "\t", "-")) and key_pattern.match(stripped):
            current = {"name": stripped[:-1], "slides": []}
            locations.append(current)
            current_slide = None
            continue

        if not current:
            continue

        if stripped.startswith("- "):
            current_slide = {}
            current["slides"].append(current_slide)
            rest = stripped[2:].strip()
            if ":" in rest:
                key, value = rest.split(":", 1)
                current_slide[key.strip()] = clean_yaml_scalar(value.strip())
            continue

        if current_slide is not None and ":" in stripped:
            key, value = stripped.split(":", 1)
            current_slide[key.strip()] = clean_yaml_scalar(value.strip())

    normalized_locations = []
    for location in locations:
        normalized_locations.append(
            {
                "name": location["name"],
                "slides": [
                    slide_from_entry(client, slide)
                    for slide in location["slides"]
                    if slide.get("name") or slide.get("file")
                ],
            }
        )

    return {"activeLocation": normalized_locations[0]["name"] if normalized_locations else "", "locations": normalized_locations}


def git_env():
    return {
        **os.environ,
        "GIT_SSH_COMMAND": f"ssh -i {GITHUB_KEY} -o IdentitiesOnly=yes -o StrictHostKeyChecking=accept-new",
    }


def run_git(repo_path, args, *, check=True, capture=True):
    proc = subprocess.run(
        ["git", "-C", str(repo_path), *args],
        check=False,
        capture_output=capture,
        text=True,
        env=git_env(),
    )
    if check and proc.returncode != 0:
        detail = (proc.stderr or proc.stdout or "").strip()
        raise RuntimeError(detail or f"git {' '.join(args)} exited {proc.returncode}")
    return proc


def git_output(repo_path, *args):
    return run_git(repo_path, list(args)).stdout.strip()


def git_status_short(repo_path):
    return git_output(repo_path, "status", "--short")


def ensure_save_preconditions(repo_path, branch):
    if git_status_short(repo_path):
        raise RuntimeError("repo checkout has local changes; run client-repo status before saving")
    run_git(repo_path, ["fetch", "origin", branch])
    local = git_output(repo_path, "rev-parse", "HEAD")
    remote = git_output(repo_path, "rev-parse", f"origin/{branch}")
    base = git_output(repo_path, "merge-base", "HEAD", f"origin/{branch}")
    if local == remote:
        return
    if local == base:
        raise RuntimeError(f"repo checkout is behind origin/{branch}; run client-repo sync before saving")
    if remote == base:
        raise RuntimeError(f"repo checkout is ahead of origin/{branch}; push or inspect it before saving")
    raise RuntimeError(f"repo checkout has diverged from origin/{branch}; inspect it before saving")


class ControlHandler(SimpleHTTPRequestHandler):
    server_version = "PromocasterControl/0.1"

    def __init__(self, *args, **kwargs):
        super().__init__(*args, directory=str(WEB_ROOT), **kwargs)

    def log_message(self, format, *args):
        print("%s - %s" % (self.address_string(), format % args), flush=True)

    def do_GET(self):
        path = urlparse(self.path).path
        if path == "/api/health":
            self.write_json(
                {
                    "ok": True,
                    "data_dir": str(DATA_DIR),
                    "repos_dir": str(REPOS_DIR),
                    "sync_dir": str(SYNC_DIR),
                    "clients_file": str(CLIENTS_FILE),
                    "clients_file_exists": CLIENTS_FILE.exists(),
                }
            )
            return
        decks_client = self.decks_client(path)
        if decks_client:
            self.write_decks(decks_client)
            return
        media_request = self.media_request(path)
        if media_request:
            self.write_media(*media_request)
            return
        sync_client = self.sync_status_client(path)
        if sync_client:
            self.write_json(self.read_sync_status(sync_client))
            return
        if path == "/":
            self.path = "/editor.html"
        elif path.startswith("/api/"):
            self.send_error(404, "API endpoint is not implemented yet")
            return
        super().do_GET()

    def do_POST(self):
        path = urlparse(self.path).path
        decks_client = self.decks_client(path)
        if decks_client:
            self.save_decks(decks_client)
            return
        self.send_error(404, "API endpoint is not implemented yet")

    def do_HEAD(self):
        media_request = self.media_request(urlparse(self.path).path)
        if media_request:
            self.write_media(*media_request, head_only=True)
            return
        super().do_HEAD()

    def translate_path(self, path):
        parsed_path = unquote(urlparse(path).path)
        if parsed_path == "/":
            parsed_path = "/editor.html"
        clean_path = posixpath.normpath(parsed_path).lstrip("/")
        target = (WEB_ROOT / clean_path).resolve()
        if WEB_ROOT not in target.parents and target != WEB_ROOT:
            return str(WEB_ROOT / "__forbidden__")
        return str(target)

    def write_json(self, payload, status=200):
        body = json.dumps(payload, indent=2).encode("utf-8")
        self.send_response(status)
        self.send_header("Content-Type", "application/json; charset=utf-8")
        self.send_header("Content-Length", str(len(body)))
        self.end_headers()
        self.wfile.write(body)

    def sync_status_client(self, path):
        parts = [part for part in path.split("/") if part]
        if len(parts) == 5 and parts[:2] == ["api", "clients"] and parts[3:] == ["sync", "status"]:
            return parts[2]
        return None

    def decks_client(self, path):
        parts = [part for part in path.split("/") if part]
        if len(parts) == 4 and parts[:2] == ["api", "clients"] and parts[3] == "decks":
            return parts[2]
        return None

    def media_request(self, path):
        parts = [part for part in path.split("/") if part]
        if len(parts) >= 5 and parts[:2] == ["api", "clients"] and parts[3] == "media":
            return parts[2], unquote("/".join(parts[4:]))
        return None

    def read_sync_status(self, client):
        status_path = SYNC_DIR / f"{client}.json"
        repo_path = REPOS_DIR / client_repo_name(client)
        if status_path.exists():
            try:
                return json.loads(status_path.read_text(encoding="utf-8"))
            except (OSError, json.JSONDecodeError) as exc:
                return {"client": client, "state": "error", "message": f"could not read sync status: {exc}"}
        if repo_path.exists():
            return {"client": client, "state": "ready", "message": "repo checkout is present", "repo_path": str(repo_path)}
        return {
            "client": client,
            "state": "not_started",
            "message": "repo has not been cloned yet; UI should start sync and keep polling this endpoint",
            "repo_path": str(repo_path),
        }

    def repo_path(self, client):
        return REPOS_DIR / client_repo_name(client)

    def write_decks(self, client):
        repo_path = self.repo_path(client)
        media_yml = repo_path / "_data" / "media.yml"
        if not repo_path.exists():
            self.write_json(
                {"error": "repo_not_synced", "message": f"run promocaster-control client-repo sync {client}"},
                status=409,
            )
            return
        if not media_yml.exists():
            self.write_json({"error": "missing_media_yml", "message": f"{media_yml} was not found"}, status=404)
            return
        try:
            self.write_json(parse_media_yml(client, media_yml))
        except (OSError, ValueError) as exc:
            self.write_json({"error": "media_yml_parse_failed", "message": str(exc)}, status=500)

    def write_media(self, client, requested_name, head_only=False):
        safe_name = posixpath.normpath("/" + requested_name).lstrip("/")
        if safe_name.startswith("../") or safe_name == "..":
            self.send_error(403)
            return

        media_path = (self.repo_path(client) / "media" / safe_name).resolve()
        media_root = (self.repo_path(client) / "media").resolve()
        if media_root not in media_path.parents and media_path != media_root:
            self.send_error(403)
            return
        if not media_path.is_file():
            self.send_error(404)
            return

        content_type = mimetypes.guess_type(media_path.name)[0] or "application/octet-stream"
        file_size = media_path.stat().st_size
        start = 0
        end = file_size - 1
        status = 200
        range_header = self.headers.get("Range")

        if range_header:
            match = re.match(r"bytes=(\d*)-(\d*)$", range_header.strip())
            if match:
                if match.group(1):
                    start = int(match.group(1))
                if match.group(2):
                    end = int(match.group(2))
                end = min(end, file_size - 1)
                if start <= end:
                    status = 206

        length = max(end - start + 1, 0)
        self.send_response(status)
        self.send_header("Content-Type", content_type)
        self.send_header("Accept-Ranges", "bytes")
        self.send_header("Content-Length", str(length))
        if status == 206:
            self.send_header("Content-Range", f"bytes {start}-{end}/{file_size}")
        self.end_headers()

        if head_only:
            return
        with media_path.open("rb") as media_file:
            media_file.seek(start)
            remaining = length
            while remaining > 0:
                chunk = media_file.read(min(1024 * 1024, remaining))
                if not chunk:
                    break
                self.wfile.write(chunk)
                remaining -= len(chunk)

    def authenticated_user(self):
        return (
            self.headers.get("X-Promocaster-User")
            or self.headers.get("Remote-User")
            or self.headers.get("X-Remote-User")
            or "unknown"
        ).strip() or "unknown"

    def read_json_body(self):
        try:
            length = int(self.headers.get("Content-Length", "0"))
        except ValueError:
            raise ValueError("invalid content length")
        if length <= 0:
            raise ValueError("empty request body")
        if length > MAX_JSON_BODY_BYTES:
            raise ValueError("request body is too large")
        return json.loads(self.rfile.read(length).decode("utf-8"))

    def save_decks(self, client):
        try:
            payload = self.read_json_body()
            repo_path = self.repo_path(client)
            branch = client_branch(client)
            media_yml = repo_path / "_data" / "media.yml"
            if not repo_path.exists():
                self.write_json(
                    {"error": "repo_not_synced", "message": f"run promocaster-control client-repo sync {client}"},
                    status=409,
                )
                return
            if not media_yml.exists():
                self.write_json({"error": "missing_media_yml", "message": f"{media_yml} was not found"}, status=404)
                return

            ensure_save_preconditions(repo_path, branch)
            before = parse_media_yml(client, media_yml)
            before_locations = location_names(before)
            after_locations = location_names(payload)
            if before_locations != after_locations:
                raise ValueError("location keys cannot be added, removed, renamed, or reordered in the editor")
            before_names = referenced_media_names(before)
            after_names = referenced_media_names(payload)
            removed_names = sorted(before_names - after_names)

            media_yml.write_text(deck_to_media_yml(payload), encoding="utf-8")
            run_git(repo_path, ["add", "_data/media.yml"])

            deleted_files = []
            for name in removed_names:
                media_path = repo_path / "media" / name
                if media_path.is_file():
                    run_git(repo_path, ["rm", "-f", "--", f"media/{name}"])
                    deleted_files.append(name)

            status = git_status_short(repo_path)
            if not status:
                self.write_json({"ok": True, "state": "no_changes", "message": "No changes to save"})
                return

            user = self.authenticated_user()
            commit_message = [
                "Update slide decks",
                "",
                f"Edited by: {user}",
                f"Client: {client}",
                "Source: Promocaster Control",
            ]
            run_git(
                repo_path,
                [
                    "-c",
                    "user.name=Promocaster Control",
                    "-c",
                    "user.email=control@promocaster.io",
                    "commit",
                    "-m",
                    commit_message[0],
                    "-m",
                    "\n".join(commit_message[2:]),
                ],
            )
            commit = git_output(repo_path, "rev-parse", "--short", "HEAD")
            run_git(repo_path, ["push", "origin", branch])
            self.write_json(
                {
                    "ok": True,
                    "state": "pushed",
                    "client": client,
                    "branch": branch,
                    "commit": commit,
                    "editedBy": user,
                    "deletedMedia": deleted_files,
                }
            )
        except json.JSONDecodeError:
            self.write_json({"error": "invalid_json", "message": "request body must be JSON"}, status=400)
        except ValueError as exc:
            self.write_json({"error": "invalid_deck", "message": str(exc)}, status=400)
        except RuntimeError as exc:
            self.write_json({"error": "save_failed", "message": str(exc)}, status=409)
        except OSError as exc:
            self.write_json({"error": "save_failed", "message": str(exc)}, status=500)


def main():
    if not WEB_ROOT.exists():
        raise SystemExit(f"web root does not exist: {WEB_ROOT}")
    SYNC_DIR.mkdir(parents=True, exist_ok=True)
    server = ThreadingHTTPServer((BIND, PORT), ControlHandler)
    print(f"Promocaster Control listening on http://{BIND}:{PORT}", flush=True)
    try:
        server.serve_forever()
    except KeyboardInterrupt:
        print("Promocaster Control stopping", flush=True)


if __name__ == "__main__":
    main()
